Yuechens fixes for functional bugs
AY2324S2-CS2103T-T12-1/tp pull request #158
Opened 2024-04-08 13:21 UTC by yuechen2001

Fixes #141 #146

2024-04-09 13:11 UTC, angsongyee requested changes

2024-04-09 13:11 UTC, angsongyee commented on src/main/java/seedu/address/logic/commands/EditCommand.java
> +     * @param index                 of the contact in the filtered contact list to edit
I think this might be accidentally added?

2024-04-09 13:11 UTC, angsongyee commented on src/main/java/seedu/address/ui/TeamListPanel.java
> +                setGraphic(new TeamCard(team, getIndex() + 1).getRoot());
Can we keep the previous change? `setPrefWidth(0)` needs to be called in each cell for layout reasons.

2024-04-10 09:00 UTC, yuechen2001 commented
> Also missing fixes for #146

Fix for #146 is under the "[Update user guide link for help command](https://github.com/AY2324S2-CS2103T-T12-1/tp/pull/158/commits/c8ad58f34400d7740aa648617e20032760b357b4)".

What I did was replace the link to the original AB3 UG to the link for our UG

2024-04-10 09:20 UTC, angsongyee commented
> > Also missing fixes for #146
> 
> Fix for #146 is under the "[Update user guide link for help command](https://github.com/AY2324S2-CS2103T-T12-1/tp/pull/158/commits/c8ad58f34400d7740aa648617e20032760b357b4)".
> 
> What I did was replace the link to the original AB3 UG to the link for our UG

The file doesn't show up in the changed files tab for some reason...

2024-04-10 09:21 UTC, angsongyee approved these changes

2024-04-10 09:23 UTC, merged