Update manual testing in DG
AY2324S2-CS2103T-T12-1/tp pull request #182
Opened 2024-04-14 09:57 UTC by angsongyee

2024-04-14 10:16 UTC, maiyasaliha requested changes, later dismissed

2024-04-14 10:16 UTC, maiyasaliha commented on docs/DeveloperGuide.md
> +1. Adding invalid contact
was this meant to be a duplicate?

2024-04-14 10:39 UTC, angsongyee commented
![image](https://github.com/AY2324S2-CS2103T-T12-1/tp/assets/29880635/92938d9b-529c-4f83-8f6e-27e1a33a5d77)

2024-04-15 15:22 UTC, yuechen2001 approved these changes

2024-04-15 15:29 UTC, merged