Update Add contact feature in User Guide
AY2324S2-CS2103T-T12-1/tp pull request #29
Opened 2024-03-06 14:56 UTC by Teee728

2024-03-06 15:03 UTC, angsongyee approved these changes
LGTM

2024-03-06 16:42 UTC, maiyasaliha requested changes
Just a few minor changes to be made. Otherwise LGTM!

2024-03-06 16:42 UTC, maiyasaliha commented on docs/UserGuide.md
> +Format: `add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS g/GITHUB_LINK [t/TAG] [ts/TECH_STACK]…​`
is this supposed to be github link or username? the first example add (on top) seems as though it is username

2024-03-06 16:42 UTC, maiyasaliha commented on docs/UserGuide.md
> +* You can remove all the person’s tags and tech stack by typing `t/` without
should this be t/ and ts/ since that is the command for tech stack we have been using so far?

2024-03-06 16:42 UTC, maiyasaliha commented on docs/UserGuide.md
> +**Add**    | `add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS g/GITHUB_LINK [t/TAG] [t/TECH_STACK]…​` <br> e.g., `add n/James Ho p/22224444 e/jamesho@example.com a/123, Clementi Rd, 1234665 g/Jamesho123
```suggestion
**Add**    | `add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS g/GITHUB_LINK [t/TAG] [ts/TECH_STACK]…​` <br> e.g., `add n/James Ho p/22224444 e/jamesho@example.com a/123, Clementi Rd, 1234665 g/Jamesho123 t/friend t/colleague ts/Java ts/C++`
```

2024-03-07 01:36 UTC, maiyasaliha approved these changes
LGTM!

2024-03-07 04:03 UTC, merged