Fix CI Badge
AY2324S2-CS2103T-T12-1/tp pull request #36
Opened 2024-03-07 11:10 UTC by tanguoyang

Point CI Badge to correct project
Fix minor issues for 2103 script

2024-03-07 11:31 UTC, Teee728 commented on docs/UserGuide.md
> +- contacts matching at least one keyword will be returned (i.e. `OR` search).
minor correction - can change "contacts" to "Contacts", but not a big deal

2024-03-07 11:33 UTC, Teee728 commented on docs/site.json
> +  "titlePrefix": "CS2103 Team-12",
Should we make it T12-1? I think the "T" in T12 stands for Thursday, 12 being our tutorial time and our actual group being group 1 in that slot

2024-03-07 11:36 UTC, angsongyee requested changes

2024-03-07 11:36 UTC, angsongyee commented on docs/AboutUs.md
> +<img src="images/teee728.png" width="200px">
Tresa's image hasn't been renamed yet so it can't find the image right now

2024-03-08 04:09 UTC, Teee728 approved these changes

2024-03-08 04:14 UTC, yuechen2001 approved these changes

2024-03-08 04:16 UTC, merged