Implement find tag command
AY2324S2-CS2103T-T12-1/tp pull request #50
Opened 2024-03-17 14:28 UTC by yuechen2001

Fixes #4 

- [ ] Add a new feature to let users search for contacts by their tags
- [ ] Update UI and wireframes on Figma
- [ ] Update DG and UG

2024-03-17 15:53 UTC, angsongyee requested changes

2024-03-17 15:53 UTC, angsongyee commented on src/main/java/seedu/address/logic/commands/FindTagCommand.java
> +    public static final String COMMAND_WORD = "findTag";
Using camel case for commands looks quite odd. Maybe `findtag` or `find-tag` would work better instead.

2024-03-17 15:53 UTC, angsongyee commented on src/test/java/seedu/address/model/person/TagsContainKeywordsPredicateTest.java
> +        assertTrue(predicate.test(new PersonBuilder().withName("Alice Bob").build()));
The tests here don't match up with the command's expected behavior.

2024-03-17 19:07 UTC, angsongyee approved these changes
LGTM

2024-03-18 04:56 UTC, maiyasaliha approved these changes
LGTM

2024-03-18 05:14 UTC, merged