Update Person to Contact and AddressBook to CodeConnect
AY2324S2-CS2103T-T12-1/tp pull request #60
Opened 2024-03-18 17:31 UTC by maiyasaliha

Updated codebase to suit terms.

2024-03-18 17:58 UTC, yuechen2001 requested changes

2024-03-18 17:58 UTC, yuechen2001 commented on LICENSE
i think the license don't need to change HAHA

2024-03-18 17:58 UTC, yuechen2001 commented on docs/diagrams/ArchitectureSequenceDiagram.puml
instead of saveAddressBook shld be saveCodeConnect?

2024-03-18 17:58 UTC, yuechen2001 commented on src/main/java/seedu/address/MainApp.java
Remove the grouping of imports

2024-03-18 17:58 UTC, yuechen2001 commented on src/main/java/seedu/address/logic/commands/EditCommand.java
Remove grouping of imports

2024-03-18 17:58 UTC, yuechen2001 commented on src/main/java/seedu/address/model/util/SampleDataUtil.java
Remove grouping of imports

2024-03-18 17:58 UTC, yuechen2001 commented on src/main/java/seedu/address/storage/JsonAdaptedContact.java
Remove grouping of imports

2024-03-18 17:58 UTC, yuechen2001 commented on src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Remove grouping of imports

2024-03-18 17:58 UTC, yuechen2001 commented on src/test/java/seedu/address/testutil/ContactBuilder.java
Remove grouping of imports

2024-03-18 17:58 UTC, yuechen2001 commented on src/test/java/seedu/address/testutil/EditContactDescriptorBuilder.java
Remove grouping of imports

2024-03-19 07:19 UTC, tanguoyang approved these changes
Looks good! Thanks for doing gods work.

Just a note for future projects, id recommend to not name any classes after brandnames, but instead calling them for what it is. eg. if its an addressbook call it an addressbook instead of codeconnect. Reason being the code might be more portable, eg, address book can be a feature inside code connect in the future, and that renaming the project/company doesnt require refactor. (Companies change name or get sold to other companies all the time) Can you imagine what would have happened to facebook's billion LoC codebase when they got renamed to Meta? o.O

anyways, good job!

2024-03-19 07:19 UTC, tanguoyang approved these changes
Looks good! Thanks for doing gods work.

Just a note for future projects, id recommend to not name any classes after brandnames, but instead calling them for what it is. eg. if its an addressbook call it an addressbook instead of codeconnect. Reason being the code might be more portable, eg, address book can be a feature inside code connect in the future, and that renaming the project/company doesnt require refactor. (Companies change name or get sold to other companies all the time) Can you imagine what would have happened to facebook's billion LoC codebase when they got renamed to Meta? o.O

anyways, good job!

2024-03-19 12:37 UTC, yuechen2001 approved these changes

2024-03-19 13:38 UTC, merged