Add tests for mail feature
AY2324S2-CS2103T-T12-1/tp pull request #62
Opened 2024-03-19 07:49 UTC by Teee728

Added tests to check if the send email directly feature works using the Mockito library to simulate the desktop behavior.

2024-03-19 15:19 UTC, yuechen2001 requested changes

2024-03-19 15:19 UTC, yuechen2001 commented on src/test/java/seedu/address/testutil/PersonBuilder.java
i think for person builder, let's only include the attributes that are non-optional. We can add tech stacks to the contacts in typicalcontacts class instead

2024-03-20 10:42 UTC, angsongyee approved these changes

2024-03-20 10:42 UTC, angsongyee commented on src/test/java/seedu/address/testutil/PersonBuilder.java
> +    //public static final String DEFAULT_TECH_STACK = "Java";
Does this need to be in the commit?

2024-03-20 10:42 UTC, angsongyee commented on src/test/java/seedu/address/testutil/PersonBuilder.java
> +        //techStack.add(new TechStack(DEFAULT_TECH_STACK));
Also here

2024-03-20 16:10 UTC, angsongyee approved these changes

2024-03-21 14:06 UTC, merged