Implement Export Team Details function + Update Contact equal() function and related tests
AY2324S2-CS2103T-T12-1/tp pull request #91
Opened 2024-03-30 13:59 UTC by yuechen2001

sorry I screwed up the commit, i accidentally merged the two commits into 1

2024-03-30 14:55 UTC, angsongyee requested changes

2024-03-30 14:55 UTC, angsongyee commented on src/main/java/seedu/address/logic/commands/ExportTeamCommand.java
> +    public static final String COMMAND_WORD = "export-team";
User should have already entered `team` as main command before this command, so this seems redundant.
```suggestion
    public static final String COMMAND_WORD = "export";
```

2024-03-30 14:55 UTC, angsongyee commented on src/main/java/seedu/address/logic/commands/ExportTeamCommand.java
> +    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Copies your team members' details to your clipboard. "
Can you add the `team` command word here? The format for team commands is slightly different, see `DeleteTeamCommand` and check output of running the `team` command for reference.

2024-03-30 14:55 UTC, angsongyee commented on src/main/java/seedu/address/logic/parser/TeamCommandsParser.java
> +            + DeleteTeamCommand.MESSAGE_USAGE
Double newline needed here for formatting.
```suggestion
            + DeleteTeamCommand.MESSAGE_USAGE + "\n\n"
```

2024-04-01 13:41 UTC, angsongyee approved these changes

2024-04-01 13:41 UTC, angsongyee commented on docs/UserGuide.md
> +Format: `INDEX export`
Actually I think we can have the full command here, otherwise it might be confusing for some users
```suggestion
Format: `team INDEX export`
```

2024-04-04 05:33 UTC, maiyasaliha approved these changes
LGTM

2024-04-04 07:18 UTC, merged