Add GUI for teams feature, update UG and DG.
AY2324S2-CS2103T-T12-1/tp pull request #98
Opened 2024-04-02 18:37 UTC by angsongyee

### GUI changes
- Team list added to GUI beside the contact list
- The minimum window size has been increased to ensure that all UI
  components are not clipped.
- All top level containers (command input, result window,
  contact/team list) now expand to fill the available space instead
  of having a fixed width/height
- Contact's tags/techstack will now overflow to a second row instead
  being truncated by the contact card's width
- Font sizes for command input and result window have been increased
  for better readability.
-----
### Tasks
- [x] Add GUI for teams feature 
- [ ] Update UG and DG

2024-04-03 08:02 UTC, yuechen2001 approved these changes
Not a GUI expert so i trust u

2024-04-03 12:18 UTC, angsongyee commented
### Updated UI Class Diagram:
![image](https://github.com/AY2324S2-CS2103T-T12-1/tp/assets/29880635/d7efdfe6-c531-42c3-aed9-de2edb6a14f8)

### Updated Model Class Diagram:
![image](https://github.com/AY2324S2-CS2103T-T12-1/tp/assets/29880635/2db650db-92df-495d-9a5d-959c96ddf256)

### New Team Class Diagram:
![image](https://github.com/AY2324S2-CS2103T-T12-1/tp/assets/29880635/b4016705-7935-4340-bbc0-6abb0eb36ab5)

2024-04-04 05:26 UTC, maiyasaliha requested changes
LGTM! Just some minor changes to be addressed before merging. Also take note of the arrowhead in fxml files, it is not huge, and honestly idk if we can avoid it in fxml. Just highlighting for code quality.

2024-04-04 05:26 UTC, maiyasaliha commented on docs/UserGuide.md
> +- Export the members' details of the team at the specified `TEAM_INDEX`.
```suggestion
- Deletes the team at the specified `TEAM_INDEX`.
```

2024-04-04 05:26 UTC, maiyasaliha commented on docs/UserGuide.md
> +- `team 1 export` deletes the first team in the team list.
```suggestion
- `team 1 delete` deletes the first team in the team list.
```

2024-04-04 05:26 UTC, maiyasaliha commented on src/main/resources/view/ContactListCard.fxml
> +<?import javafx.scene.layout.*?>
Wildcard Imports

2024-04-04 05:26 UTC, maiyasaliha commented on src/main/resources/view/MainWindow.fxml
> +<?import javafx.stage.*?>
Wildcard Imports

2024-04-04 11:53 UTC, yuechen2001 approved these changes

2024-04-04 12:16 UTC, angsongyee commented
Normal width:
![image](https://github.com/AY2324S2-CS2103T-T12-1/tp/assets/29880635/31896d3a-27f8-4d14-a529-3e470837f01b)
Narrow width:
![image](https://github.com/AY2324S2-CS2103T-T12-1/tp/assets/29880635/89605a63-24c8-4132-a0b2-73a6e25da976)

2024-04-04 12:32 UTC, Teee728 commented on docs/UserGuide.md
> +- TEAM_NAME can only contain alphanumeric characters and spaces and cannot be blank.
minor change, can do `TEAM_NAME` instead

2024-04-04 13:12 UTC, Teee728 approved these changes
LGTM!

2024-04-04 13:19 UTC, merged